FROM node:18-slim

RUN apt-get update && apt-get install -y openssl

RUN npm i -g pnpm typescript

WORKDIR /usr/src/app

COPY package.json ./
RUN pnpm install

COPY tsconfig.json ./
COPY src ./src

RUN pnpm build

EXPOSE 8080

CMD ["pnpm", "start"]
